feat: IMMENSE!!!

diff --git a/linux/.local/scripts/crun b/linux/.local/scripts/crun
--- a/linux/.local/scripts/crun
+++ b/linux/.local/scripts/crun
@@ -1,54 +1,52 @@
 #!/usr/bin/env bash
 
-
-_marker="${PROJECT_ROOT_MARKER:-.edis}"
-
 source "$HOME/.local/scripts/lib/logging.sh"
 source "$HOME/.local/scripts/lib/require.sh"
-require find-project-root gcc
+require find-project-root
 
 while [[ "$#" -gt 0 ]]; do
-    case "$1" in
-        -q | --quiet)
-            info() { :; }
-            warning() { :; }
-            success() { :; }
-            quiet="true"
-            shift
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1" && exit 1
-            ;;
-        *)
-            break
-            ;;
-    esac
+  case "$1" in
+    -q | --quiet)
+      LOG_INFO() { :; }
+      LOG_WARN() { :; }
+      LOG_DONE() { :; }
+      quiet="true"
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*)
+      LOG_ERROR "Unknown option: $1" && exit 1
+      ;;
+    *)
+      break
+      ;;
+  esac
 done
 
 main() {
-    [[ "$#" -gt 1 ]] && error "too many arguments (expected 1 or less)" && exit 1
+  [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected 1 or less)" && exit 1
 
-    local project_root=$(find-project-root "$_marker" 2>/dev/null)
-    if [[ -z "$project_root" ]]; then
-        error "root marker '$_marker' not found" && exit 1
-    fi
+  marker="${PROJECT_ROOT_MARKER:-.edis.toml}"
+  local project_root=$(find-project-root "$marker" 2>/dev/null)
+  if [[ -z "$project_root" ]]; then
+    LOG_ERROR "root marker '$marker' not found" && exit 1
+  fi
 
-    local build_dir="$project_root/build"
-    local project_name="$(basename $project_root)"
-    local program_name="${1:-$project_name}"
-    local program="$build_dir/$program_name"
+  local build_dir="$project_root/build"
+  local project_name="$(basename $project_root)"
+  local program_name="${1:-$project_name}"
+  local program="$build_dir/$program_name"
 
-    [[ ! -f "$program" ]] && error "program not found: '$program_name'" && exit 1
+  [[ ! -f "$program" ]] && LOG_ERROR "program not found: '$program_name'" && exit 1
+  [[ ! -x "$program" ]] && LOG_ERROR "program not executable: '$program_name'" && exit 1
 
-    [[ -x "$program" ]] \
-    && info "detected program $program" \
-    && info "executing program: $program_name" \
-    && $program \
-    && exit 0
+  LOG_INFO "found program $program" \
+  && LOG_INFO "executing program: $program_name" \
+  && $program \
+  && exit $?
 }
 
 main "$@"
diff --git a/linux/.local/scripts/find-project-root b/linux/.local/scripts/find-project-root
--- a/linux/.local/scripts/find-project-root
+++ b/linux/.local/scripts/find-project-root
@@ -16,28 +16,28 @@ EOF
 
 _find_project_root() {
 
-    local marker="${1:-$PROJECT_ROOT_MARKER}"
+  local marker="${1:-$PROJECT_ROOT_MARKER}"
 
-    if [[ -z "$marker" ]]; then
-        error "PROJECT_ROOT_MARKER is not set, must pass root marker as argument." && exit 1
+  if [[ -z "$marker" ]]; then
+    LOG_ERROR "PROJECT_ROOT_MARKER is not set, must pass root marker as argument." && exit 1
+  fi
+
+  local current_dir=$(pwd -P) || { LOG_ERROR "pwd failed?"; exit 1; }
+  while [[ "$current_dir" != "/" ]]; do
+
+    if [[ -e "$current_dir/$marker" ]]; then
+      echo "$current_dir" && return 0
     fi
 
-    local current_dir=$(pwd -P) || (error "pwd failed?" && exit 1)
-    while [[ "$current_dir" != "/" ]]; do
+    current_dir=$(dirname "$current_dir")
+  done
 
-        if [[ -e "$current_dir/$marker" ]]; then
-            echo "$current_dir" && return 0
-        fi
-
-        current_dir=$(dirname "$current_dir")
-    done
-
-    error "could not locate '$marker' root marker." && exit 1
+  LOG_ERROR "could not locate '$marker' root marker." && exit 1
 }
 
 main() {
-    [[ "$1" == "help" ]] && _help && exit 0
-    _find_project_root "$@"
+  [[ "$1" == "help" ]] && _help && exit 0
+  _find_project_root "$@"
 }
 
 main "$@"
diff --git a/linux/.local/scripts/javab b/linux/.local/scripts/javab
--- a/linux/.local/scripts/javab
+++ b/linux/.local/scripts/javab
@@ -2,70 +2,77 @@
 
 shopt -s globstar
 
-_marker="${PROJECT_ROOT_MARKER:-.edis}"
-
 source "$HOME/.local/scripts/lib/logging.sh"
 source "$HOME/.local/scripts/lib/require.sh"
 require find-project-root javac
 
 while [[ "$#" -gt 0 ]]; do
-    case "$1" in
-        -q | --quiet)
-            info() { return 0; }
-            warning() { return 0; }
-            success() { return 0; }
-            quiet="true"
-            shift
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            error "Unknown option: $1" && exit 1
-            ;;
-        *)
-            break
-            ;;
-    esac
+  case "$1" in
+    -q | --quiet)
+      LOG_INFO() { :; }
+      LOG_WARN() { :; }
+      LOG_DONE() { :; }
+      quiet="true"
+      shift
+      ;;
+    -qq | --qquiet)
+      LOG_INFO() { :; }
+      LOG_WARN() { :; }
+      LOG_DONE() { :; }
+      LOG_ERROR() { :; }
+      qquiet="true"
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*)
+      LOG_ERROR "Unknown option: $1" && exit 1
+      ;;
+    *)
+      break
+      ;;
+  esac
 done
 
 _compile_source_files() {
-    local source_files=$1
-    local source_dir=$2
-    local build_dir=$3
+  local source_files=$1
+  local source_dir=$2
+  local build_dir=$3
+  shift 3
 
-    info "attempting to compile source files:"
-    for source_file in $source_files; do
-        local file_relative_to_src_dir=$(realpath --relative-to="$source_dir" "$source_file")
-        [[ -z "$quiet" ]] && echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.java}.class"
-    done
+  LOG_INFO "attempting to compile source files:"
+  for source_file in $source_files; do
+    local file_relative_to_src_dir="${source_file#$source_dir/}"
+    [[ -z "$quiet" && -z "$qquiet" ]] && echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.java}.class" >&2
+  done
 
-    local grep_result="$(grep -rE '^\s*public static void main' $source_dir)"
-    if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
-        warning "multiple main methods detected"
-    fi
+  local grep_main
+  grep_main="$(grep -rE '^\s*public static void main' $source_dir)"
+  [[ -z "$grep_main" ]]                 && LOG_WARN "no main method detected"
+  [[ $(wc -l <<< "$grep_main") -gt 1 ]] && LOG_WARN "multiple main methods detected"
 
-    javac -d $build_dir $source_files && return 0 || error "failed to compile" && return 1
+  javac -d "$build_dir" $source_files || { LOG_ERROR "failed to compile"; return 1; }
 }
 
 main() {
-    local project_root=$(find-project-root "$_marker" 2>/dev/null)
+  local project_root
+  local marker="${PROJECT_ROOT_MARKER:-.edis.toml}"
+  project_root=$(find-project-root "$marker" 2>/dev/null)
+  if [[ -z "$project_root" ]]; then
+    LOG_ERROR "root marker '$marker' not found" && exit 1
+  fi
 
-    if [[ -z "$project_root" ]]; then
-        error "root marker '$_marker' not found" && exit 1
-    fi
+  local build_dir="$project_root/build"
+  local source_dir="$project_root/src"
+  local source_files=$project_root/src/**/*.java
 
-    local build_dir="$project_root/build"
-    local source_dir="$project_root/src"
-    local source_files=$project_root/src/**/*.java
-
-    # && javac -d $build_dir $source_files || error "failed to compile" \
-    mkdir -pv "$build_dir" \
-    && info "building project into $build_dir..." \
-    && _compile_source_files "$source_files" "$source_dir" "$build_dir" \
-    && success "built project into $build_dir" \
-    && exit 0
+  mkdir -p "$build_dir" \
+  && LOG_INFO "building project into $build_dir..." \
+  && _compile_source_files "$source_files" "$source_dir" "$build_dir" \
+  && LOG_DONE "built project into $build_dir" \
+  && exit 0
 }
 
 main "$@"
