scripts: use jq instead of toml

diff --git a/linux/.local/scripts/crun b/linux/.local/scripts/crun
--- a/linux/.local/scripts/crun
+++ b/linux/.local/scripts/crun
@@ -29,8 +29,13 @@ done
 main() {
   [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected 1 or less)" && exit 1
 
-  marker="${PROJECT_ROOT_MARKER:-.edis.toml}"
-  local project_root=$(find-project-root "$marker" 2>/dev/null)
+  local project_root
+  project_root=$(
+    find-project-root "$PROJECT_ROOT_MARKER" 2>/dev/null ||
+    find-project-root ".edis.json" 2>/dev/null ||
+    find-project-root ".edis.toml" 2>/dev/null
+  )
+
   if [[ -z "$project_root" ]]; then
     LOG_ERROR "root marker '$marker' not found" && exit 1
   fi
@@ -40,7 +45,7 @@ main() {
   local program_name="${1:-$project_name}"
   local program="$build_dir/$program_name"
 
-  [[ ! -f "$program" ]] && LOG_ERROR "program not found: '$program_name'" && exit 1
+  [[ ! -f "$program" ]] && LOG_ERROR "program not found: '$program_name'"      && exit 1
   [[ ! -x "$program" ]] && LOG_ERROR "program not executable: '$program_name'" && exit 1
 
   LOG_INFO "found program $program" \
diff --git a/linux/.local/scripts/javab b/linux/.local/scripts/javab
--- a/linux/.local/scripts/javab
+++ b/linux/.local/scripts/javab
@@ -53,15 +53,19 @@ _compile_source_files() {
   [[ -z "$grep_main" ]]                 && LOG_WARN "no main method detected"
   [[ $(wc -l <<< "$grep_main") -gt 1 ]] && LOG_WARN "multiple main methods detected"
 
-  javac -d "$build_dir" $source_files || { LOG_ERROR "failed to compile"; return 1; }
+  # echo "javac -d $build_dir $@ $source_files"
+  javac -d "$build_dir" "$@" $source_files || { LOG_ERROR "failed to compile"; return 1; }
 }
 
 main() {
   local project_root
-  local marker="${PROJECT_ROOT_MARKER:-.edis.toml}"
-  project_root=$(find-project-root "$marker" 2>/dev/null)
+  project_root=$(
+    find-project-root "$PROJECT_ROOT_MARKER" 2>/dev/null ||
+    find-project-root ".edis.json" 2>/dev/null ||
+    find-project-root ".edis.toml" 2>/dev/null
+  )
   if [[ -z "$project_root" ]]; then
-    LOG_ERROR "root marker '$marker' not found" && exit 1
+    LOG_ERROR "root marker '$marker' not found"; exit 1
   fi
 
   local build_dir="$project_root/build"
@@ -70,7 +74,7 @@ main() {
 
   mkdir -p "$build_dir" \
   && LOG_INFO "building project into $build_dir..." \
-  && _compile_source_files "$source_files" "$source_dir" "$build_dir" \
+  && _compile_source_files "$source_files" "$source_dir" "$build_dir" "$@" \
   && LOG_DONE "built project into $build_dir" \
   && exit 0
 }
diff --git a/linux/.local/scripts/javar b/linux/.local/scripts/javar
--- a/linux/.local/scripts/javar
+++ b/linux/.local/scripts/javar
@@ -1,80 +1,83 @@
 #!/usr/bin/env bash
 
 
-_marker="${PROJECT_ROOT_MARKER:-.edis.toml}"
-
 source "$HOME/.local/scripts/lib/logging.sh"
 source "$HOME/.local/scripts/lib/require.sh"
 require find-project-root java
 
 while [[ "$#" -gt 0 ]]; do
-    case "$1" in
-        -q | --quiet)
-            LOG_INFO() { :; }
-            LOG_WARN() { :; }
-            LOG_DONE() { :; }
-            quiet="true"
-            shift
-            ;;
-        -qq | --qquiet)
-            LOG_INFO() { :; }
-            LOG_WARN() { :; }
-            LOG_DONE() { :; }
-            LOG_ERROR() { :; }
-            qquiet="true"
-            shift
-            ;;
-        --)
-            shift
-            break
-            ;;
-        -*)
-            LOG_ERROR "Unknown option: $1" && exit 1
-            ;;
-        *)
-            break
-            ;;
-    esac
+  case "$1" in
+    -q | --quiet)
+      LOG_INFO() { :; }
+      LOG_WARN() { :; }
+      LOG_DONE() { :; }
+      quiet="true"
+      shift
+      ;;
+    -qq | --qquiet)
+      LOG_INFO() { :; }
+      LOG_WARN() { :; }
+      LOG_DONE() { :; }
+      LOG_ERROR() { :; }
+      qquiet="true"
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*)
+      LOG_ERROR "Unknown option: $1" && exit 1
+      ;;
+    *)
+      break
+      ;;
+  esac
 done
 
 main() {
-    [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected 1 or less)" && exit 1
+  # [[ "$#" -gt 1 ]] && LOG_ERROR "too many arguments (expected 1 or less)" && exit 1
 
-    local project_root=$(find-project-root "$_marker" 2>/dev/null)
+  local project_root
+  project_root=$(
+    find-project-root "$PROJECT_ROOT_MARKER" 2>/dev/null ||
+    find-project-root ".edis.json" 2>/dev/null ||
+    find-project-root ".edis.toml" 2>/dev/null
+  )
 
-    if [[ -z "$project_root" ]]; then
-        LOG_ERROR "root marker '$_marker' not found" && exit 1
-    fi
+  if [[ -z "$project_root" ]]; then
+    LOG_ERROR "root marker '$_marker' not found" && exit 1
+  fi
 
-    local build_dir="$project_root/build"
-    local src_dir="$project_root/src"
+  local build_dir="$project_root/build"
+  local src_dir="$project_root/src"
 
-    if [[ "$#" -eq 0 ]]; then
-        local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
+  # if [[ "$#" -eq 0 ]]; then
+  local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
 
-        if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
-            LOG_ERROR "multiple main methods detected" && return 1
-        fi
+  if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
+    LOG_ERROR "multiple main methods detected" && return 1
+  fi
 
-        if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
-            LOG_ERROR "no main method detected" && return 1
-        fi
+  if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
+    LOG_ERROR "no main method detected" && return 1
+  fi
 
-        local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
-        local main_name=$(basename "$main_file" ".java")
-    else
-        local main_name="$1"
-    fi
+  local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
+  local main_name=$(basename "$main_file" ".java")
+  # else
+  # local main_name="$1"
+  # fi
 
-    local main_class=$(find "$build_dir" -name "$main_name.class")
-    [[ -z "$main_class" ]] && LOG_ERROR "could not locate class file: 'build/$main_name.class'"
-    local rel_path_to_main="${main_class#$build_dir/}"
-    rel_path_to_main="${rel_path_to_main%.*}"
+  local main_class=$(find "$build_dir" -name "$main_name.class")
+  [[ -z "$main_class" ]] && LOG_ERROR "could not locate class file: 'build/$main_name.class'"
+  local rel_path_to_main="${main_class#$build_dir/}"
+  rel_path_to_main="${rel_path_to_main%.*}"
 
-    LOG_INFO "class path: $build_dir" \
-    && LOG_INFO "executing main() in: $rel_path_to_main" \
-    && java -cp "$build_dir" "$rel_path_to_main" "$@" \
-    && return 0
+  LOG_INFO "class path: $build_dir" \
+  && LOG_INFO "executing main() in: $rel_path_to_main" \
+  && java -cp "$build_dir" "$rel_path_to_main" "$@" \
+  && return 0
 }
 
 main "$@"
