feat: c-build scripts

diff --git a/.local/scripts/edis b/.local/scripts/edis
--- a/.local/scripts/edis
+++ b/.local/scripts/edis
@@ -3,16 +3,25 @@
 
 root_marker=".$(basename "$0")"
 
-error() {
+error()
+{
     local errmsg="$1"
-    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
+    if [[ -t 1 ]]; then
+        echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
+    else
+        echo -e "[ERROR] $(basename $0): $msg"
+    fi
     exit 1
 }
 
 success()
 {
     local msg="$1"
-    echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
+    if [[ -t 1 ]]; then
+        echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
+    else
+        echo -e "[SUCCESS] $(basename "$0"): $msg"
+    fi
     return 0
 }
 
@@ -24,7 +33,8 @@ _init()
     touch "$root_marker" && exit 0
 }
 
-_create() {
+_create()
+{
     local project_name=""
     local dirs_to_mk=""
 
diff --git a/.local/scripts/find-project-root b/.local/scripts/find-project-root
--- a/.local/scripts/find-project-root
+++ b/.local/scripts/find-project-root
@@ -1,11 +1,6 @@
 #!/usr/bin/env bash
 
-
-die() {
-    local errmsg="$1"
-    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
-    exit 1
-}
+source "$HOME/.local/scripts/lib/logging.sh"
 
 _help() {
     cat <<-EOF
@@ -24,10 +19,10 @@ _find_project_root() {
     local marker="${1:-$PROJECT_ROOT_MARKER}"
 
     if [[ -z "$marker" ]]; then
-        die "PROJECT_ROOT_MARKER is not set, must pass root marker as argument."
+        error "PROJECT_ROOT_MARKER is not set, must pass root marker as argument."
     fi
 
-    local current_dir=$(pwd -P) || die "pwd failed?"
+    local current_dir=$(pwd -P) || error "pwd failed?"
     while [[ "$current_dir" != "/" ]]; do
 
         if [[ -e "$current_dir/$marker" ]]; then
@@ -37,7 +32,7 @@ _find_project_root() {
         current_dir=$(dirname "$current_dir")
     done
 
-    die "could not locate '$marker' root marker."
+    error "could not locate '$marker' root marker."
 }
 
 main() {
diff --git a/.local/scripts/javab b/.local/scripts/javab
--- a/.local/scripts/javab
+++ b/.local/scripts/javab
@@ -5,47 +5,35 @@ shopt -s globstar
 _find_project_root="find-project-root"
 _marker="${PROJECT_ROOT_MARKER:-.edis}"
 
-error()
-{
-    local msg="$1"
-    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $msg >&2
-    exit 1
-}
-
-info()
-{
-    local msg="$1"
-    echo -e "[\e[1;34mINFO\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
-    return 0
-}
-
-success()
-{
-    local msg="$1"
-    echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
-    return 0
-}
+source "$HOME/.local/scripts/lib/logging.sh"
 
 if ! command -v "$_find_project_root" &> /dev/null; then
-    error "could not find '$_find_project_root' command."
+    error "could not find '$_find_project_root' command." && exit 1
 fi
+
 if ! command -v javac &> /dev/null; then
-    error "could not find 'javac' command."
+    error "could not find 'javac' command." && exit 1
 fi
 
 _compile_source_files()
 {
     # this breaks relative imports for the compiler for some reason
     local source_files=$1
-    local build_dir=$2
+    local source_dir=$2
+    local build_dir=$3
 
+    info "attempting to compile source files:"
     for source_file in $source_files; do
-        echo "javac -d $build_dir $source_file"
-        javac -d $build_dir $source_file || error "javac failed"
-        info "compiled $(basename $source_file)"
+        local file_relative_to_src_dir=$(realpath --relative-to="$source_dir" "$source_file")
+        echo -e "\t$file_relative_to_src_dir -> ${file_relative_to_src_dir%.java}.class"
     done
 
-    return 0
+    local grep_result="$(grep -rE '^\s*public static void main' $source_dir)"
+    if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
+        warning "multiple main methods detected"
+    fi
+
+    javac -d $build_dir $source_files && return 0 || error "failed to compile" && return 1
 }
 
 main()
@@ -53,16 +41,17 @@ main()
     local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)
 
     if [[ -z "$project_root" ]]; then
-        error "root marker '$_marker' not found"
+        error "root marker '$_marker' not found" && exit 1
     fi
 
     local build_dir="$project_root/build"
+    local source_dir="$project_root/src"
     local source_files=$project_root/src/**/*.java
 
-    # && _compile_source_files "$source_files" "$build_dir" \
+    # && javac -d $build_dir $source_files || error "failed to compile" \
     mkdir -pv "$build_dir" \
     && info "building project into $build_dir..." \
-    && javac -d $build_dir $source_files \
+    && _compile_source_files "$source_files" "$source_dir" "$build_dir" \
     && success "built project into $build_dir" \
     && exit 0
 }
diff --git a/.local/scripts/javar b/.local/scripts/javar
--- a/.local/scripts/javar
+++ b/.local/scripts/javar
@@ -4,19 +4,14 @@
 _find_project_root="find-project-root"
 _marker="${PROJECT_ROOT_MARKER:-.edis}"
 
-error()
-{
-    local errmsg="$1"
-    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
-    exit 1
-}
+source "$HOME/.local/scripts/lib/logging.sh"
 
 if ! command -v "$_find_project_root" &> /dev/null; then
-    error "could not find '$_find_project_root' command"
+    error "could not find '$_find_project_root' command" && exit 1
 fi
 
 if ! command -v java &> /dev/null; then
-    error "could not find 'java' command"
+    error "could not find 'java' command" && exit 1
 fi
 
 main()
@@ -28,16 +23,15 @@ main()
     fi
 
     local build_dir="$project_root/build"
-    # local src_dir="$project_root/src/main/java"
     local src_dir="$project_root/src"
     local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
 
     if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
-        error "multiple main methods detected"
+        error "multiple main methods detected" && return 1
     fi
 
     if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
-        error "no main method detected"
+        error "no main method detected" && return 1
     fi
 
     local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
@@ -46,7 +40,10 @@ main()
     local rel_path_to_main="${main_class#$build_dir/}"
     rel_path_to_main="${rel_path_to_main%.*}"
 
-    java -cp "$build_dir" "$rel_path_to_main" && return 0
+    info "class path: $build_dir" \
+    && info "executing main() in: $rel_path_to_main" \
+    && java -cp "$build_dir" "$rel_path_to_main" \
+    && return 0
 }
 
 main "$@"
