feat: add/update custom system utilities

diff --git a/.local/scripts/edis b/.local/scripts/edis
--- a/.local/scripts/edis
+++ b/.local/scripts/edis
@@ -3,15 +3,23 @@
 
 root_marker=".$(basename "$0")"
 
-die() {
+error() {
     local errmsg="$1"
-    echo "$(basename "$0"): [ERROR]" $errmsg >&2
+    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
     exit 1
 }
 
-_init() {
+success()
+{
+    local msg="$1"
+    echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
+    return 0
+}
+
+_init()
+{
     if [[ -f "$root_marker" ]]; then
-        die "'$root_marker' file already exists."
+        error "'$root_marker' file already exists."
     fi
     touch "$root_marker" && exit 0
 }
@@ -27,7 +35,8 @@ _create() {
                 shift
                 ;;
             --java)
-                dirs_to_mk="src/main/java"
+                # dirs_to_mk="src/main/java"
+                dirs_to_mk="src/ build/"
                 shift
                 ;;
             -n|--name)
@@ -36,26 +45,26 @@ _create() {
                 shift
                 ;;
             *)
-                die "unknown argument: $1"
+                error "unknown argument: $1"
                 ;;
         esac
     done
 
     if [[ -z "$dirs_to_mk" ]]; then
-        die "must specify project type."
+        error "must specify project type."
     fi
     if [[ -z "$project_name" ]]; then
-        die "must specify project name with 'name' argument."
+        error "must specify project name with 'name' argument."
     fi
     if [[ -e "$project_name" ]]; then
-        die "project with name '$project_name' already exists."
+        error "project with name '$project_name' already exists."
     fi
 
     mkdir -p $project_name \
     && cd $project_name \
     && mkdir -p $dirs_to_mk \
     && touch "$root_marker" \
-    && echo "$(basename "$0"): [SUCCESS] created project '$project_name' in '$(pwd)'" \
+    && success "created project '$project_name' in '$(pwd)'" \
     && exit 0
 }
 
@@ -65,7 +74,7 @@ _help() {
     [[ "$1" == "init" ]] && _init_help && exit 0
     [[ "$1" == "create" ]] && _create_help && exit 0
 
-    die "'$1' is not a recognized subcommand, must be either 'init' or 'create'"
+    error "'$1' is not a recognized subcommand, must be either 'init' or 'create'"
 }
 
 _main_help() {
@@ -123,7 +132,7 @@ main() {
             _help "$@"
             ;;
         *)
-            die "unknown subcommand: $cmd"
+            error "unknown subcommand: $cmd"
             ;;
     esac
 }
diff --git a/.local/scripts/find-project-root b/.local/scripts/find-project-root
--- a/.local/scripts/find-project-root
+++ b/.local/scripts/find-project-root
@@ -3,7 +3,7 @@
 
 die() {
     local errmsg="$1"
-    echo "$(basename "$0"): [ERROR]" $errmsg >&2
+    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
     exit 1
 }
 
diff --git a/.local/scripts/javab b/.local/scripts/javab
--- a/.local/scripts/javab
+++ b/.local/scripts/javab
@@ -1,43 +1,59 @@
 #!/usr/bin/env bash
 
-
 shopt -s globstar
 
 _find_project_root="find-project-root"
 _marker="${PROJECT_ROOT_MARKER:-.edis}"
 
-die() {
+error()
+{
     local msg="$1"
-    echo "$(basename "$0"): [ERROR]" $msg >&2
+    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $msg >&2
     exit 1
 }
 
+info()
+{
+    local msg="$1"
+    echo -e "[\e[1;34mINFO\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
+    return 0
+}
+
+success()
+{
+    local msg="$1"
+    echo -e "[\e[1;32mSUCCESS\e[0m] \e[36m$(basename "$0")\e[0m: $msg"
+    return 0
+}
+
 if ! command -v "$_find_project_root" &> /dev/null; then
-    die "could not find '$_find_project_root' command."
+    error "could not find '$_find_project_root' command."
 fi
 if ! command -v javac &> /dev/null; then
-    die "could not find 'javac' command."
+    error "could not find 'javac' command."
 fi
 
-_compile_source_files() {
+_compile_source_files()
+{
     # this breaks relative imports for the compiler for some reason
     local source_files=$1
     local build_dir=$2
 
     for source_file in $source_files; do
         echo "javac -d $build_dir $source_file"
-        javac -d $build_dir $source_file || die "javac failed"
-        echo "$(basename "$0"): [INFO] compiled $(basename $source_file)"
+        javac -d $build_dir $source_file || error "javac failed"
+        info "compiled $(basename $source_file)"
     done
 
     return 0
 }
 
-main() {
+main()
+{
     local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)
 
     if [[ -z "$project_root" ]]; then
-        die "root marker '$_marker' not found"
+        error "root marker '$_marker' not found"
     fi
 
     local build_dir="$project_root/build"
@@ -45,9 +61,9 @@ main() {
 
     # && _compile_source_files "$source_files" "$build_dir" \
     mkdir -pv "$build_dir" \
-    && echo "$(basename "$0"): [INFO] building project into $build_dir..." \
+    && info "building project into $build_dir..." \
     && javac -d $build_dir $source_files \
-    && echo "$(basename "$0"): [SUCCESS] built project into $build_dir" \
+    && success "built project into $build_dir" \
     && exit 0
 }
 
diff --git a/.local/scripts/javar b/.local/scripts/javar
--- a/.local/scripts/javar
+++ b/.local/scripts/javar
@@ -4,38 +4,40 @@
 _find_project_root="find-project-root"
 _marker="${PROJECT_ROOT_MARKER:-.edis}"
 
-die() {
+error()
+{
     local errmsg="$1"
-    echo "$(basename "$0"): [ERROR]" $errmsg >&2
+    echo -e "[\e[1;31mERROR\e[0m] \e[36m$(basename "$0")\e[0m:" $errmsg >&2
     exit 1
 }
 
 if ! command -v "$_find_project_root" &> /dev/null; then
-    die "could not find '$_find_project_root' command."
+    error "could not find '$_find_project_root' command"
 fi
 
 if ! command -v java &> /dev/null; then
-    die "could not find 'java' command."
+    error "could not find 'java' command"
 fi
 
-main() {
-
+main()
+{
     local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)
 
     if [[ -z "$project_root" ]]; then
-        die "root marker '$_marker' not found."
+        error "root marker '$_marker' not found"
     fi
 
     local build_dir="$project_root/build"
-    local src_dir="$project_root/src/main/java"
+    # local src_dir="$project_root/src/main/java"
+    local src_dir="$project_root/src"
     local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
 
     if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
-        die "multiple main methods detected."
+        error "multiple main methods detected"
     fi
 
     if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
-        die "no main method detected."
+        error "no main method detected"
     fi
 
     local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
