feat(scripts): update java build scripts

diff --git a/.local/scripts/javar b/.local/scripts/javar
--- a/.local/scripts/javar
+++ b/.local/scripts/javar
@@ -1,42 +1,64 @@
 #!/usr/bin/env bash
 
 
-_find_project_root="find-project-root"
 _marker="${PROJECT_ROOT_MARKER:-.edis}"
 
 source "$HOME/.local/scripts/lib/logging.sh"
+source "$HOME/.local/scripts/lib/require.sh"
+require find-project-root java
 
-if ! command -v "$_find_project_root" &> /dev/null; then
-    error "could not find '$_find_project_root' command" && exit 1
-fi
+while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+        -q | --quiet)
+            info() { return 0; }
+            warning() { return 0; }
+            success() { return 0; }
+            quiet="true"
+            shift
+            ;;
+        --)
+            shift
+            break
+            ;;
+        -*)
+            error "Unknown option: $1" && exit 1
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
 
-if ! command -v java &> /dev/null; then
-    error "could not find 'java' command" && exit 1
-fi
+main() {
+    [[ "$#" -gt 1 ]] && error "too many arguments (expected 1 or less)" && exit 1
 
-main()
-{
-    local project_root=$("$_find_project_root" "$_marker" 2>/dev/null)
+    local project_root=$(find-project-root "$_marker" 2>/dev/null)
 
     if [[ -z "$project_root" ]]; then
-        error "root marker '$_marker' not found"
+        error "root marker '$_marker' not found" && exit 1
     fi
 
     local build_dir="$project_root/build"
     local src_dir="$project_root/src"
-    local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
 
-    if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
-        error "multiple main methods detected" && return 1
+    if [[ "$#" -eq 0 ]]; then
+        local grep_result="$(grep -rE '^\s*public static void main' $src_dir)"
+
+        if [[ $(wc -l <<< "$grep_result") -gt 1 ]]; then
+            error "multiple main methods detected" && return 1
+        fi
+
+        if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
+            error "no main method detected" && return 1
+        fi
+
+        local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
+        local main_name=$(basename "$main_file" ".java")
+    else
+        local main_name="$1"
     fi
-
-    if [[ $(wc -l <<< "$grep_result") -eq 0 ]]; then
-        error "no main method detected" && return 1
-    fi
-
-    local main_file=$(cut -d ':' -f 1 <<< "$grep_result")
-    local main_name=$(basename "$main_file" ".java")
     local main_class=$(find "$build_dir" -name "$main_name.class")
+    [[ -z "$main_class" ]] && error "could not locate class file: 'build/$main_name.class'"
     local rel_path_to_main="${main_class#$build_dir/}"
     rel_path_to_main="${rel_path_to_main%.*}"
 
